# golangci-lint configuration for AlternateDNS
# This config excludes CGO packages that don't have export data

run:
  timeout: 5m
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
  # Skip CGO packages that don't have export data
  skip-packages:
    - github.com/go-gl/gl
    - github.com/go-gl/gl/v2.1/gl
    - github.com/fyne-io/gl-js
    - github.com/fyne-io/glfw-js

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude test files from errcheck
    - path: _test\.go
      linters:
        - errcheck

linters:
  disable-all: false
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
  # Disable linters that require export data for CGO packages
  disable:
    - typecheck  # This requires export data which CGO packages don't have

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: MaxIsJoe/AlternateDNS

